name: Master

on:
  push:
    branches: [ master ]

jobs:
  CI:
    name: Check master branch
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Install node modules
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test-with-coverage

      - name: Build
        run: yarn build

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
